-- XCR8 Growth attribution foundation (production-safe migration)
-- Phase 1: additive schema only. No existing subscription, payment, usage,
-- authentication, or content state is modified.

CREATE TABLE IF NOT EXISTS growth_campaigns (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_code VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(180) NOT NULL,
    description TEXT,
    campaign_type VARCHAR(64) NOT NULL DEFAULT 'marketing',
    status VARCHAR(24) NOT NULL DEFAULT 'active',
    destination_url TEXT,
    attribution_window_days INTEGER NOT NULL DEFAULT 30,
    created_by_user_id INTEGER NOT NULL REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_growth_campaign_window CHECK (attribution_window_days BETWEEN 1 AND 3650)
);

CREATE INDEX IF NOT EXISTS ix_growth_campaigns_status
    ON growth_campaigns (status);
CREATE INDEX IF NOT EXISTS ix_growth_campaigns_created_by
    ON growth_campaigns (created_by_user_id);

CREATE TABLE IF NOT EXISTS influencer_referrals (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    influencer_name VARCHAR(180) NOT NULL,
    contact_email VARCHAR(255),
    contact_phone VARCHAR(40),
    notes TEXT,
    status VARCHAR(24) NOT NULL DEFAULT 'active',
    campaign_id INTEGER REFERENCES growth_campaigns(id),
    compensation_type VARCHAR(32) NOT NULL DEFAULT 'none',
    compensation_plan VARCHAR(64),
    cash_compensation NUMERIC(20, 2) NOT NULL DEFAULT 0,
    attribution_window_days INTEGER NOT NULL DEFAULT 30,
    created_by_user_id INTEGER NOT NULL REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_influencer_window CHECK (attribution_window_days BETWEEN 1 AND 3650),
    CONSTRAINT ck_influencer_cash_compensation CHECK (cash_compensation >= 0)
);

CREATE INDEX IF NOT EXISTS ix_influencer_referrals_status
    ON influencer_referrals (status);
CREATE INDEX IF NOT EXISTS ix_influencer_referrals_campaign
    ON influencer_referrals (campaign_id);
CREATE INDEX IF NOT EXISTS ix_influencer_referrals_created_by
    ON influencer_referrals (created_by_user_id);

CREATE TABLE IF NOT EXISTS referral_codes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(80) NOT NULL UNIQUE,
    code_type VARCHAR(24) NOT NULL,
    campaign_id INTEGER REFERENCES growth_campaigns(id),
    influencer_referral_id INTEGER REFERENCES influencer_referrals(id),
    owner_user_id INTEGER REFERENCES users(id),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_referral_code_owner_count CHECK (
        (CASE WHEN campaign_id IS NOT NULL THEN 1 ELSE 0 END) +
        (CASE WHEN influencer_referral_id IS NOT NULL THEN 1 ELSE 0 END) +
        (CASE WHEN owner_user_id IS NOT NULL THEN 1 ELSE 0 END) <= 1
    )
);

CREATE INDEX IF NOT EXISTS ix_referral_codes_type_active
    ON referral_codes (code_type, active);
CREATE INDEX IF NOT EXISTS ix_referral_codes_campaign
    ON referral_codes (campaign_id);
CREATE INDEX IF NOT EXISTS ix_referral_codes_influencer
    ON referral_codes (influencer_referral_id);
CREATE INDEX IF NOT EXISTS ix_referral_codes_owner_user
    ON referral_codes (owner_user_id);

CREATE TABLE IF NOT EXISTS watermark_links (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creator_user_id INTEGER NOT NULL REFERENCES users(id),
    content_post_id INTEGER REFERENCES content_posts(id),
    public_code VARCHAR(80) NOT NULL UNIQUE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_watermark_links_creator
    ON watermark_links (creator_user_id);
CREATE INDEX IF NOT EXISTS ix_watermark_links_content_post
    ON watermark_links (content_post_id);
CREATE INDEX IF NOT EXISTS ix_watermark_links_active
    ON watermark_links (active);

CREATE TABLE IF NOT EXISTS attribution_visits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tracking_id VARCHAR(80) NOT NULL UNIQUE,
    referral_code VARCHAR(80),
    campaign_id INTEGER REFERENCES growth_campaigns(id),
    influencer_referral_id INTEGER REFERENCES influencer_referrals(id),
    watermark_id INTEGER REFERENCES watermark_links(id),
    visitor_token VARCHAR(128) NOT NULL,
    landing_url TEXT,
    referrer_url TEXT,
    utm_source VARCHAR(160),
    utm_medium VARCHAR(160),
    utm_campaign VARCHAR(160),
    utm_content VARCHAR(160),
    first_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_attribution_visits_visitor_token
    ON attribution_visits (visitor_token);
CREATE INDEX IF NOT EXISTS ix_attribution_visits_referral_code
    ON attribution_visits (referral_code);
CREATE INDEX IF NOT EXISTS ix_attribution_visits_campaign
    ON attribution_visits (campaign_id);
CREATE INDEX IF NOT EXISTS ix_attribution_visits_influencer
    ON attribution_visits (influencer_referral_id);
CREATE INDEX IF NOT EXISTS ix_attribution_visits_watermark
    ON attribution_visits (watermark_id);
CREATE INDEX IF NOT EXISTS ix_attribution_visits_first_seen
    ON attribution_visits (first_seen_at);

CREATE TABLE IF NOT EXISTS acquisition_attributions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL UNIQUE REFERENCES users(id),

    first_touch_type VARCHAR(24),
    first_touch_referral_code VARCHAR(80),
    first_touch_campaign_id INTEGER REFERENCES growth_campaigns(id),
    first_touch_influencer_id INTEGER REFERENCES influencer_referrals(id),
    first_touch_watermark_id INTEGER REFERENCES watermark_links(id),
    first_touch_at TIMESTAMPTZ,

    last_touch_type VARCHAR(24),
    last_touch_referral_code VARCHAR(80),
    last_touch_campaign_id INTEGER REFERENCES growth_campaigns(id),
    last_touch_influencer_id INTEGER REFERENCES influencer_referrals(id),
    last_touch_watermark_id INTEGER REFERENCES watermark_links(id),
    last_touch_at TIMESTAMPTZ,

    attribution_window_days INTEGER NOT NULL DEFAULT 30,
    signup_at TIMESTAMPTZ,
    activation_at TIMESTAMPTZ,
    first_paid_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT ck_acquisition_window CHECK (attribution_window_days BETWEEN 1 AND 3650)
);

CREATE INDEX IF NOT EXISTS ix_acquisition_attributions_first_touch
    ON acquisition_attributions (first_touch_type, first_touch_at);
CREATE INDEX IF NOT EXISTS ix_acquisition_attributions_last_touch
    ON acquisition_attributions (last_touch_type, last_touch_at);
CREATE INDEX IF NOT EXISTS ix_acquisition_attributions_campaign
    ON acquisition_attributions (first_touch_campaign_id, last_touch_campaign_id);
CREATE INDEX IF NOT EXISTS ix_acquisition_attributions_influencer
    ON acquisition_attributions (first_touch_influencer_id, last_touch_influencer_id);

CREATE TABLE IF NOT EXISTS referral_relationships (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    referrer_user_id INTEGER NOT NULL REFERENCES users(id),
    referred_user_id INTEGER NOT NULL UNIQUE REFERENCES users(id),
    referral_code VARCHAR(80),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_referral_relationship_not_self CHECK (referrer_user_id <> referred_user_id)
);

CREATE INDEX IF NOT EXISTS ix_referral_relationships_referrer
    ON referral_relationships (referrer_user_id);
CREATE INDEX IF NOT EXISTS ix_referral_relationships_code
    ON referral_relationships (referral_code);

CREATE TABLE IF NOT EXISTS growth_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER REFERENCES users(id),
    campaign_id INTEGER REFERENCES growth_campaigns(id),
    influencer_referral_id INTEGER REFERENCES influencer_referrals(id),
    referral_code VARCHAR(80),
    watermark_id INTEGER REFERENCES watermark_links(id),
    referrer_user_id INTEGER REFERENCES users(id),
    event_type VARCHAR(64) NOT NULL,
    event_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_growth_events_user_time
    ON growth_events (user_id, event_time);
CREATE INDEX IF NOT EXISTS ix_growth_events_type_time
    ON growth_events (event_type, event_time);
CREATE INDEX IF NOT EXISTS ix_growth_events_campaign_time
    ON growth_events (campaign_id, event_time);
CREATE INDEX IF NOT EXISTS ix_growth_events_influencer_time
    ON growth_events (influencer_referral_id, event_time);
CREATE INDEX IF NOT EXISTS ix_growth_events_referrer_time
    ON growth_events (referrer_user_id, event_time);
CREATE INDEX IF NOT EXISTS ix_growth_events_watermark_time
    ON growth_events (watermark_id, event_time);


-- Phase 4: persist verified payment economics for revenue attribution.
ALTER TABLE payment_events
    ADD COLUMN IF NOT EXISTS currency VARCHAR(8),
    ADD COLUMN IF NOT EXISTS amount_minor BIGINT,
    ADD COLUMN IF NOT EXISTS billing_cycle VARCHAR(16);

CREATE INDEX IF NOT EXISTS idx_payment_events_user_created
    ON payment_events (user_id, processed_at);


-- Growth admin creation is authenticated by the existing admin access-code system,
-- which does not identify a row in public.users. Keep source creation audit fields nullable
-- until admin identities are introduced.
ALTER TABLE growth_campaigns
    ALTER COLUMN created_by_user_id DROP NOT NULL;

ALTER TABLE influencer_referrals
    ALTER COLUMN created_by_user_id DROP NOT NULL;
